services:
  db:
    image: postgres:16
    container_name: lab10-postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword123
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"

  vault:
    image: hashicorp/vault:latest
    container_name: lab10-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
